apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster-elk-bv
spec:
  version: 8.9.1
  nodeSets:
  - name: master-nodes
    count: 3
    config:
        node.roles: ["master"]
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 20Gi   # Tamanho do disco solicitado por pod  
    podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "8Gi"
                  cpu: "4" 
  - name: data-nodes
    count: 3
    config:
        node.roles: ["data","ingest","transform","data_content"]
        #node.attr.data: hot
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "standard"
          resources:
            requests:
              storage: 20Gi   # Tamanho do disco solicitado por pod   
    podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "8Gi"
                  cpu: "4"        
#  - name: data-frozen
#    count: 2
#    config:
#        node.roles: ["data_frozen"]
#        node.attr.data: frozen
#    volumeClaimTemplates:
#      - metadata:
#          name: elasticsearch-data
#        spec:
#          accessModes: [ "ReadWriteOnce" ]
#          storageClassName: "standard"
#          resources:
#            requests:
#              storage: 50Gi   # Tamanho do disco solicitado por pod         
#    podTemplate:
#        spec:
#          containers:
#            - name: elasticsearch
#              resources:
#                requests:
#                  memory: "4Gi"
#                  cpu: "2"
#                limits:
#                  memory: "8Gi"
#                  cpu: "4"
# - name: ml
#    count: 1
#    config:
#        node.roles: [ ml, remote_cluster_client]
#        node.attr.data: ml
#    volumeClaimTemplates:
#      - metadata:
#          name: elasticsearch-data
#        spec:
#          accessModes: [ "ReadWriteOnce" ]
#          storageClassName: "standard"
#          resources:
#            requests:
#              storage: 20Gi   # Tamanho do disco solicitado por pod  
#    podTemplate:
#        spec:
#          containers:
#            - name: elasticsearch
#              resources:
#                requests:
#                  memory: "4Gi"
#                  cpu: "2"
#                limits:
#                  memory: "8Gi"
#                  cpu: "4"

